### ISSUE TITLE
Hyperlink href attributes on html not parsed.

### ISSUE THREAD

**Issue by FGMGIT** [nightwill/WPArticleView#1]
The href found in html text actually are not parsed, could you please help with that, in the [SwiftSoup](https://github.com/scinfu/SwiftSoup) package seems to be possible.

**Comment by nightwill** [comment]
> The href found in html text actually are not parsed, could you please help with that, in the [SwiftSoup](https://github.com/scinfu/SwiftSoup) package seems to be possible.

@FGMGIT If it's still relevant, could you give me please a piece of html code for the test.

**Comment by FGMGIT** [comment]
Sorry for my late reply.

Sure you can try just inserting a link in your wordpress, any link in your text like `<a href="https://google.com/"><span style="font-weight: 400;">Google Page</span></a>` will be parsed only with the title "Google Page" not parsing hyperlink or the href tag losing the link.

Consequently you lose the information of the link on the APP. As stated on  [SwiftSoup](https://github.com/scinfu/SwiftSoup#parse-a-document-from-a-string) library this is posible

**Comment by nightwill** [comment]
@FGMGIT I fixed it. Please use `attributedText` parameter instead of `text` (I updated README)

**Comment by FGMGIT** [comment]
Hi thank you, now is parsing href tags, but the whole text in the post content is not taking font type and special characters like "º" or "á" or "ñ". are not recognized.

And trying to force it with  .font() modifier doesn't work

**Comment by nightwill** [comment]
I think it's a limitation of `NSAttributedString` or `AttributedString`. Sorry I can't help you there.
